

class RandomGenerator{
	constructor(minValue,maxValue){ 
		//takes in the minimum and maximum values
		//if they are not defined, it sets the minimum to 1, and the max to 10
		//makes storage for the random number
		this.minValue=minValue;
		this.maxValue=maxValue;
		
		this.randomNumber = this.generate(minValue,maxValue);

	}
	generate(minValue=1, maxValue=10){
		//make a random value between the minimum and maximum values
		//and store the number into the storage from the constructor
		return Math.floor(Math.random() * this.maxValue) + this.minValue;
	}
	getRange(minValue,maxValue){
		//return an object with min and max, min being the minimum value for the generator, max being the maximum value
		//returns a basic object literal
		return {min:this.minValue,max:this.maxValue}
	}
	getNum(){
		//return the random number that was generated by generate()
		return this.generate();
	}
}